site_name: Numbat
site_description: Documentation
site_author: Chris Green
site_url: http://cpgr.github.io/numbat
copyright: Copyright &copy; 2017 Chris Green (chris.green@csiro.au)
theme: readthedocs
repo_url: https://github.com/cpgr/numbat/

pages:
  - Overview: index.md
  - Getting started: getting-started.md
  - Theory: governing-equations.md
  - Syntax: input-file-syntax.md
  - Examples:
      - 2D example: example2D.md
      - 3D example: example3D.md
  - References: references.md
  - Download PDF: download.md

markdown_extensions:
  - figureAltCaption

extra_javascript: ['https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML', 'js/mathjaxhelper.js']

extra_css: ['css/extra.css']
